### PR TITLE
Polish/stats fixes

### PR DESCRIPTION
**Pull request by nightsreach21**
- [x] Builds and Runs without bugs on Android

- [x] Builds and Runs without bugs on iOS

- [x] Switches between menu states without bugs 20 times consecutively

### CODE REVIEW

**Comment by jonjondev** [comment]
Yeah so the current changes do not fix stats at all (2nd time always breaks for me), however because it fixes my bug, I'm tempted to merge it anyway... @jacobvorr how would you feel about this?

**Comment by nightsreach21** [comment]
> Yeah so the current changes do not fix stats at all (2nd time always breaks for me), however because it fixes my bug, I'm tempted to merge it anyway...

What is the behavior you get? 
The expected behavior is for the stats to animate around the building and always face the camera. That is all I changed.

**Comment by jonjondev** [comment]
> What is the behavior you get?

Essentially everything works, however switching between menu states breaks the stats animations all the time.

**Review by jonjondev — APPROVED** [review]
Working as expected.

**Pull request merged**
